name: dca-site-environment
channels:
  #- defaults
  - conda-forge
  - tiagoantao
dependencies:
  - poppler
  - numpy
  - pdf2image
  - abjad
  #- jupyter_nbextensions_configurator
  #- jupyter_contrib_nbextensions
